# Generated by Django 5.0.2 on 2024-02-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('also_known_as', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('batting_style', models.CharField(choices=[('Left Hand', 'Left Hand'), ('Right Hand', 'Right Hand')], max_length=55)),
                ('bowling_style', models.CharField(choices=[('Left arm Fast', 'Left arm Fast'), ('Left arm Leg Spin', 'Left arm Leg Spin'), ('Left arm Medium', 'Left arm Medium'), ('Left arm Medium Fast', 'Left arm Medium Fast'), ('Left arm Off Spin', 'Left arm Off Spin'), ('Right arm Fast', 'Right arm Fast'), ('Right arm Leg Spin', 'Right arm Leg Spin'), ('Right arm Medium', 'Right arm Medium'), ('Right arm Medium Fast', 'Right arm Medium Fast'), ('Right arm Off Spin', 'Right arm Off Spin')], max_length=55)),
                ('playing_role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('AllRounder', 'All-Rounder'), ('WicketKeeper', 'WicketKeeper')], max_length=55)),
                ('created_by', models.CharField(default='Initial', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Player Info',
            },
        ),
        migrations.CreateModel(
            name='PlayerBatting',
            fields=[
                ('batting_id', models.IntegerField(default=1100, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('Test', 'Test'), ('ODI', 'ODI'), ('T20', 'T20')], max_length=4)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('innings', models.IntegerField(blank=True, null=True)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('hs', models.IntegerField(blank=True, null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('bf', models.IntegerField(blank=True, null=True)),
                ('sr', models.FloatField(blank=True, null=True)),
                ('centuries', models.IntegerField(blank=True, null=True)),
                ('fifties', models.IntegerField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('sixes', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_api.player')),
            ],
            options={
                'verbose_name_plural': 'Batting Stats',
            },
        ),
        migrations.CreateModel(
            name='PlayerBowling',
            fields=[
                ('bowling_id', models.IntegerField(default=1100, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('Test', 'Test'), ('ODI', 'ODI'), ('T20', 'T20')], max_length=4)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('wickets', models.IntegerField(blank=True, null=True)),
                ('innings', models.IntegerField(blank=True, null=True)),
                ('overs', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('bbi', models.CharField(blank=True, max_length=10, null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('econ', models.FloatField(blank=True, null=True)),
                ('sr', models.FloatField(blank=True, null=True)),
                ('four_ws', models.IntegerField(blank=True, null=True)),
                ('five_ws', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_api.player')),
            ],
            options={
                'verbose_name_plural': 'Bowling Stats',
            },
        ),
        migrations.CreateModel(
            name='PlayerWicketKeeping',
            fields=[
                ('wicketkeeping_id', models.IntegerField(default=1100, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('Test', 'Test'), ('ODI', 'ODI'), ('T20', 'T20')], max_length=4)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('innings', models.IntegerField(blank=True, null=True)),
                ('catches', models.IntegerField(blank=True, null=True)),
                ('stumping', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_api.player')),
            ],
            options={
                'verbose_name_plural': 'WicketKeeping Stats',
            },
        ),
    ]
