# Generated by Django 5.0.2 on 2024-03-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbowling',
            name='overs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
